/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';

export namespace Components {
  interface AppProfile {
    'match': MatchResults;
  }
  interface LunaGame {
    'match': MatchResults;
  }
  interface LunaHome {}
  interface LunaPlayer {
    'address': string;
  }
  interface LunaRoot {}
}

declare global {


  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLLunaGameElement extends Components.LunaGame, HTMLStencilElement {}
  var HTMLLunaGameElement: {
    prototype: HTMLLunaGameElement;
    new (): HTMLLunaGameElement;
  };

  interface HTMLLunaHomeElement extends Components.LunaHome, HTMLStencilElement {}
  var HTMLLunaHomeElement: {
    prototype: HTMLLunaHomeElement;
    new (): HTMLLunaHomeElement;
  };

  interface HTMLLunaPlayerElement extends Components.LunaPlayer, HTMLStencilElement {}
  var HTMLLunaPlayerElement: {
    prototype: HTMLLunaPlayerElement;
    new (): HTMLLunaPlayerElement;
  };

  interface HTMLLunaRootElement extends Components.LunaRoot, HTMLStencilElement {}
  var HTMLLunaRootElement: {
    prototype: HTMLLunaRootElement;
    new (): HTMLLunaRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-profile': HTMLAppProfileElement;
    'luna-game': HTMLLunaGameElement;
    'luna-home': HTMLLunaHomeElement;
    'luna-player': HTMLLunaPlayerElement;
    'luna-root': HTMLLunaRootElement;
  }
}

declare namespace LocalJSX {
  interface AppProfile {
    'match'?: MatchResults;
  }
  interface LunaGame {
    'match'?: MatchResults;
  }
  interface LunaHome {}
  interface LunaPlayer {
    'address'?: string;
  }
  interface LunaRoot {}

  interface IntrinsicElements {
    'app-profile': AppProfile;
    'luna-game': LunaGame;
    'luna-home': LunaHome;
    'luna-player': LunaPlayer;
    'luna-root': LunaRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'luna-game': LocalJSX.LunaGame & JSXBase.HTMLAttributes<HTMLLunaGameElement>;
      'luna-home': LocalJSX.LunaHome & JSXBase.HTMLAttributes<HTMLLunaHomeElement>;
      'luna-player': LocalJSX.LunaPlayer & JSXBase.HTMLAttributes<HTMLLunaPlayerElement>;
      'luna-root': LocalJSX.LunaRoot & JSXBase.HTMLAttributes<HTMLLunaRootElement>;
    }
  }
}


