/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';

export namespace Components {
  interface LunaField {
    'middle': boolean;
    'name': string;
    'value': number;
  }
  interface LunaGame {
    'match': MatchResults;
  }
  interface LunaHome {
    'history': RouterHistory;
  }
  interface LunaPlayer {
    'address': string;
  }
  interface LunaRoot {}
}

declare global {


  interface HTMLLunaFieldElement extends Components.LunaField, HTMLStencilElement {}
  var HTMLLunaFieldElement: {
    prototype: HTMLLunaFieldElement;
    new (): HTMLLunaFieldElement;
  };

  interface HTMLLunaGameElement extends Components.LunaGame, HTMLStencilElement {}
  var HTMLLunaGameElement: {
    prototype: HTMLLunaGameElement;
    new (): HTMLLunaGameElement;
  };

  interface HTMLLunaHomeElement extends Components.LunaHome, HTMLStencilElement {}
  var HTMLLunaHomeElement: {
    prototype: HTMLLunaHomeElement;
    new (): HTMLLunaHomeElement;
  };

  interface HTMLLunaPlayerElement extends Components.LunaPlayer, HTMLStencilElement {}
  var HTMLLunaPlayerElement: {
    prototype: HTMLLunaPlayerElement;
    new (): HTMLLunaPlayerElement;
  };

  interface HTMLLunaRootElement extends Components.LunaRoot, HTMLStencilElement {}
  var HTMLLunaRootElement: {
    prototype: HTMLLunaRootElement;
    new (): HTMLLunaRootElement;
  };
  interface HTMLElementTagNameMap {
    'luna-field': HTMLLunaFieldElement;
    'luna-game': HTMLLunaGameElement;
    'luna-home': HTMLLunaHomeElement;
    'luna-player': HTMLLunaPlayerElement;
    'luna-root': HTMLLunaRootElement;
  }
}

declare namespace LocalJSX {
  interface LunaField {
    'middle'?: boolean;
    'name'?: string;
    'onFieldSelected'?: (event: CustomEvent<any>) => void;
    'value'?: number;
  }
  interface LunaGame {
    'match'?: MatchResults;
  }
  interface LunaHome {
    'history'?: RouterHistory;
  }
  interface LunaPlayer {
    'address'?: string;
  }
  interface LunaRoot {}

  interface IntrinsicElements {
    'luna-field': LunaField;
    'luna-game': LunaGame;
    'luna-home': LunaHome;
    'luna-player': LunaPlayer;
    'luna-root': LunaRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'luna-field': LocalJSX.LunaField & JSXBase.HTMLAttributes<HTMLLunaFieldElement>;
      'luna-game': LocalJSX.LunaGame & JSXBase.HTMLAttributes<HTMLLunaGameElement>;
      'luna-home': LocalJSX.LunaHome & JSXBase.HTMLAttributes<HTMLLunaHomeElement>;
      'luna-player': LocalJSX.LunaPlayer & JSXBase.HTMLAttributes<HTMLLunaPlayerElement>;
      'luna-root': LocalJSX.LunaRoot & JSXBase.HTMLAttributes<HTMLLunaRootElement>;
    }
  }
}


