name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      # Build dist folder
      - name: Build
        run: npm install && npm run build

      # Deploy dist folder to GH pages
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          target_branch: gh-pages
          build_dir: www
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
